name: TicketBooking-Pipeline
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # This allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Starting the CI process..."

      - name: Run a multi-line script
        run: |
          echo "Building application..."
          echo "Testing application..."
          echo "Success!"
